### ISSUE TITLE
This example project fails out of the box

### ISSUE THREAD

**Issue by the-simian** [pubnub/react-native-tutorial#26]
Something has caused react-native projects to fail when including any core modules from node. This used to work, but for some reason, now it doesn't. In this case, the 'url' module is the one that is failing, but installing that from npm just moves the error to the next missing module:

```
Unable to resolve module url from 
Users/<username>/src/react-native-tutorial/node_modules/proxy-agent/index.js: 
unable to find this module in its module map 
or any of the node_modules directories under 
/Users/node_modules/url and its parent directories
```

![image](https://cloud.githubusercontent.com/assets/954596/22676562/c611b47e-ecb1-11e6-869f-46761ced21fd.png)

It could be http, crypto, tls - if it is a core module, react-native breaks atm.

**Comment by the-simian** [comment]
I found the issue: 

**You Broke Semver**

This issue should be submitted in your /javascript project, but you do not seem to accept issues there from the public atm. When you added an entirely new dependency `superagent-proxy`, you added a bunch of core node modules as subdependencies that cause react-native to fail. TLS, url, http and others.

here is the breaking commit: https://github.com/pubnub/javascript/commit/d71cbde2111cea7b5e1c924b677051976a34a606#diff-9ce18a76a03026ee81afb25b83608ba9


here is the semver specification as well: http://semver.org/

```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```

so you can see that a Patch is a bugfix, a minor version is adding functionality (which you did) and a major change is when you make a change that  is not backwards compatible. At the very least the functionality added is a Minor update, and since it does break platforms, I'd  say its probably a Major, based on semver.

**Comment by MaxPresman** [comment]
The inclusion of the proxy agent into the react native build was unintentional. We have published a new build which re-routes react native builds into its own entry point and isolating it from the node paths. (1cf5d5ae2139)

In the future, we are going to reduce the superagent dependency in those builds.
