### ISSUE TITLE
React-Native tutorial config issue

### ISSUE THREAD

**Issue by klusurf** [pubnub/react-native-tutorial#27]
I followed the instructions for the react-native-tutorial here - https://github.com/pubnub/react-native-tutorial - but I immediately got an error regarding the config file.
 
I configured the Github and PubNub OAuth (& other related) keys and tried to run the app via the "npm run server ios &" command but I keep getting this error -
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PubNub/server/index.js:17
const {config} = require('../config');
      ^
 
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I also used the default project Github and PubNub keys but I still get the same error.

Is anyone else having the same issue? Thanks for any help.

**Comment by MaxPresman** [comment]
@klusurf what version of node are you running? can you run it against latest node version

**Comment by klusurf** [comment]
Sorry, should've updated to the latest version of node before writing up the issue. We're good now. ;-)
